winget install Docker.DockerDesktop -e
winget install Git.Git -e
winget install GitHub.cli -e
winget install JanDeDobbeleer.OhMyPosh -e
winget install Meld.Meld -e
winget install Microsoft.PowerShell -e
winget install Neovim.Neovim -e
winget install Obsidian.Obsidian -e
winget install Postman.Postman -e
winget install junegunn.fzf -e
winget install zig.zig -e
